site_name: DMC Extensibility Bootcamp
site_url: ""
repo_url: "https://github.com/SAP-samples/digital-manufacturing-extension-samples"

theme:
    name: null
    custom_dir: 'docs/theme/material'
    logo: 'assets/logo_sap.jpeg'
    favicon: assets/favicon.png
    language: 'en'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    feature:
        tabs: true
    palette:
        primary: 'black'
        accent: 'blue'
extra_css:
    - 'theme/stylesheets/extra.css'

nav:
    - Bootcamp Agenda:
        -  'Content': 'index.md'
    - Participant Guide:
        -  'Content': 'ParticipantGuide.md'

markdown_extensions:
    - attr_list
    - admonition             # block-styled content like "!!! note"
    - footnotes              # footnotes; references with [^1] inline and decl's with [^1]: Lorem ipsum, ...
    - toc:
        permalink: True 