site_name: DMC Extensibility Bootcamp
site_url: https://pages.github.tools.sap/DigitalManufacturingExtensions/DMC-Extensibility-Bootcamp-Participant-Guide/
repo_url: https://github.tools.sap/DigitalManufacturingExtensions/DMC-Extensibility-Bootcamp-Participant-Guide/

theme:
    name: null
    custom_dir: 'docs/theme/material'
    logo: 'assets/logo_sap.jpeg'
    favicon: assets/favicon.png
    language: 'en'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    feature:
        tabs: true
    palette:
        primary: 'black'
        accent: 'blue'
extra_css:
    - 'theme/stylesheets/extra.css'

nav:
    - Bootcamp Agenda:
        -  'Content': 'index.md'
    - Participant Guide:
        -  'Content': 'ParticipantGuide.md'

markdown_extensions:
    - attr_list
    - admonition             # block-styled content like "!!! note"
    - footnotes              # footnotes; references with [^1] inline and decl's with [^1]: Lorem ipsum, ...
    - toc:
        permalink: True 